### ISSUE TITLE
Transformation Review Questions

### ISSUE THREAD

**Issue by Alalo1** [cisc3620/review#18]
Hi guys, I'm having a difficult time understanding how to get the answers for questions 4 and 5 on the transformations midterm review questions.
4. Create a matrix to translate a point 3 in the x direction and -1 in the y direction and 3 in the z direction, and then scale a point 3.51 along the y-axis, and then rotate a point 1,29 radians around the z-axis.

5. Create a matrix to scale a point 2.05 along the x-axis and 0.92 along the y-axis and 1.59 along the z-axis, and then rotate a point 1.70 radians around the z-axis, and then translate a point 4 in the x direction and 3 in the y direction.

Any help would be appreciated! TIA

**Comment by rivlev** [comment]
See #15

**Comment by Mohamed-Alguhiem** [comment]
ANSWER TO NUMBER 4

REMEBER YOUR MULTIPLICATION ORDER SHOULD BE (TRSP)
so let us start by rotating

Step 1: rotate  1.29 radians Note: Make sure your calculator is on Radians.
The identity matrix is:   YOU MUST MEMORIZE THIS FOR THE EXAM

[cos(delta) -sin(delta) 0 0]
[sin(delta) cos(delta)]
[0 0 1 0]
[0 0 0 1]

Now get COS(1.29) and SIN(1.29) in radians then replace them in the identity matrix.
So rotating matrix solution is:
[0.277 -0.961 0 0]
[0.961 0.277 0 0]
[0 0 1 0]
[0 0 0 1]

Step 2:SCALE  3.51 along the y-axis.
The identity matrix is: YOU MUST MEMORIZE THIS FOR EXAM
Sx 0 0 0 
0 Sy 0 0 
0 0 Sz 0
0 0 0 1

This should be easy you are only told to scale along the y-axis by 3.51. so change the Sy to 3.51 and the Sx  Sz let them be 1 since you are not scaling by them.

So SCALING matrix solution is:
[1  0 0 0]
[0 3.51 0 0]
[0 0 1 0]
[0 0 0 1]


Step 3:  TRANSLATE  3 in the x direction and -1 in the y direction and 3 in the
z direction
The identity matrix is: YOU MUST MEMORIZE THIS FOR EXAM
1 0 0 tx 
0 1 0 ty 
0 0 1 tz
0 0 0 1

so the translated matrix should look like this
1 0 0 3 
0 1 0 -1 
0 0 1 3
0 0 0 1

step 4: FOLLOW TRSP to Multiply but go backward when multiplying because your working from end to start. so it will be (Scale Matrix)*(Rotate Matrix) 

1  0 0 0]
[0 3.51 0 0]
[0 0 1 0]
[0 0 0 1]

x

[0.277 -0.961 0 0]
[0.961 0.277  0 0]
[0 0 1 0]
[0 0 0 1]
 
=
[0.277 -3.37 0 3]
[0.961 0.972  0 -1]
[0 0 1 0]
[0 0 0 1]

NOTE: If you don't know how to multiply 4x4 matrix look at this video
https://www.youtube.com/watch?v=sYlOjyPyX3g


FINAL STEP: Multiply  Translated matrix with the solution matrix from the previous step.

[0.277 -3.37 0 3]
[0.961 0.972  0 -1]
[0 0 1 0]
[0 0 0 1]
x

1 0 0 3 
0 1 0 -1 
0 0 1 3
0 0 0 1
=
[0.277 -3.37 0 4.201]
[0.961 0.972  0 1.91]
[0 0 1 3]
[0 0 0 1]

**Comment by Mohamed-Alguhiem** [comment]
Number 5 do the same steps for 4. Remember to work backward. and when you Multiply do SRT.

**Comment by DenisBarabanov** [comment]
hey bro used a calculator on the matrix and it seems i am getting different answers
http://www.calcul.com/show/calculator/matrix-multiplication_;4;4;4;4?matrix1=[[%221%22,%220%22,%220%22,%220%22],[%220%22,%223.51%22,%220%22,%220%22],[%220%22,%220%22,%221%22,%220%22],[%220%22,%220%22,%220%22,%221%22]]&matrix2=[[%220.28%22,%22-0.96%22,%220%22,%220%22],[%220.96%22,%2200.28%22,%220%22,%220%22],[%220%22,%220%22,%221%22,%220%22],[%220%22,%220%22,%220%22,%221%22]]&operator=*


and then i take that and multiply it by 1 0 0 3, 0 1 0 -1, 0 0 1 3, 0 0 0 1

http://www.calcul.com/show/calculator/matrix-multiplication_;4;4;4;4?matrix1=[[%220.28%22,%22-0.96%22,%220%22,%220%22],[%223.36%22,%220.98%22,%220%22,%220%22],[%220%22,%220%22,%221%22,%220%22],[%220%22,%220%22,%220%22,%221%22]]&matrix2=[[%221%22,%220%22,%220%22,%223%22],[%220%22,%221%22,%220%22,%221.9%22],[%220%22,%220%22,%221%22,%223%22],[%220%22,%220%22,%220%22,%221%22]]&operator=*

**Comment by DenisBarabanov** [comment]
i think u mean rotate matrix * scale matrix....otherwise i get different numbers...but the exactly what u got when i do rotate by scale

**Comment by Mohamed-Alguhiem** [comment]
rotate * scale 
then
whatever u get from that * translate

**Comment by DenisBarabanov** [comment]
hey for number 5 just want to make sure i got it right
ROTATION
-0.12 -0.99 0 0
0.99 -0.12 0 0 
0 0 1 0
0 0 0 1

SCALE
2.05 0 0 0
0 0.92 0 0
0 0 1.59 0
0 0 0 1

TRANSLATE
1 0 0 4
0 1 0 3
0 0 1 0
0 0 0 1
------- 
rotate * scale
then answer * translate
CORRECT? Ill post the answer in a sec after i multiply them out

**Comment by DenisBarabanov** [comment]
Rotation * Scale
ANSWER
-0.25 -2.03 0 0
0.9  -0.1  0 0
0 0 1.59 0 0 
0 0 0 1
 then Multiply that by Translate
1 0 0 4
0 1 0 3
0 0 1 0
0 0 0 1


not getting the same result...as the answer sheet....

**Comment by Mohamed-Alguhiem** [comment]
you are doing something wrong with your calculation. don't stress it. you will still get more than half credit if your logic is correct. Focus on other problems.
The transformation review is easy compared to lighting and viewing reviews.

**Comment by Mohamed-Alguhiem** [comment]
wait why is ur translate 
1 0 0 4
0 1 0 3
0 0 1 0
0 0 0 1

**Comment by Mohamed-Alguhiem** [comment]
also why is your rotations matrix 
-0.12 -0.99 0 0
0.99 -0.12 0 0
0 0 1 0
0 0 0 1

**Comment by Mohamed-Alguhiem** [comment]
look at my explanation you will see the identity matrix there. Follow them. You are making easy mistakes.

**Comment by Mohamed-Alguhiem** [comment]
if you are doing 5 then your translate matrix should be 
1 0 0 4
0 1 0 3
0 0 1 1
0 0 0 1

**Comment by DenisBarabanov** [comment]
ok it must of been cause of the 1 i missed in translation matrix
but doing 
[cos(1.70) -sin(1.70) 0 0]
[sin(1.70) cos(1.70)]
[0 0 1 0]
[0 0 0 1]
=
-0.12 -0.99 0 0
0.99 -0.12 0 0
0 0 1 0
0 0 0 1

yea calculator set to rad

**Comment by Mohamed-Alguhiem** [comment]
ignore what i said about tz

**Comment by DenisBarabanov** [comment]
so 
1 0 0 4
0 1 0 3
0 0 1 0
0 0 0 1

is correct?

**Comment by Mohamed-Alguhiem** [comment]
yes am working on it give me 3 minutes

**Comment by DenisBarabanov** [comment]
ohhh sorry got coffee flowing through my veins lol

**Comment by DenisBarabanov** [comment]
you going to be on campus early? want to meet up?

**Comment by DenisBarabanov** [comment]
i also added u on facebook and im going to message u my phone number, can u text me when ur headed to campus or call me?

**Comment by Mohamed-Alguhiem** [comment]
SRT PROBLEM ORDER 
Rotation Matrix
-0.129 -0.992 0 0
0.992 -0.12 0 0
0 0 1 0
0 0 0 1
______________________________________

Scaling Matrix
2.05 0 0 0
0 0.92 0 0
0 0 1.59 0
0 0 0 1
____________ ____________________________
Translated Matrix
1 0 0 4
0 1 0 3
0 0 1 0
0 0 0 1

S*R=
0.28 -0.96 0 0 
3.3696 0.9828 0 0
0 0 1 0
0 0 0 1

T*R = 0.28  −0.96  0   0
           3.37  0.98   0    0 
          0         0        1    0
          0         0         0  1

i did (T*R)* s
and (S*R)* T 

for both my result is different.

I gave up i think there is problem with the question try a different question number which is similar  
am going to sleep.
